### PR TITLE
closes #80 improve readability of articles

### LINKED ISSUE #80: ADRS and ADTTE example improvements
A lot of the `head()` calls show exactly the same extract and its not really that useful to show them, so will remove as per ADPC and ADPPK examples.

### PR DESCRIPTION
**Pull request by rossfarrugia**
## Pull Request

Make ADRS and ADTTE examples more readable by removing all the head() calls showing the same thing each time.

Before you submit your pull request, take a look at the following checklist. Many thanks for your contribution! 

- [x] **Title:** Place `Closes #<insert_issue_number>` at the beginning of your PR title. Use the Edit button in the top-right if you need to update.
- [x] **Linked Issue:** Ensure the related issue is linked in the "Development Section" on the right-hand side.
- [x] **First Contribution:** If this is your first contribution, add yourself to the `DESCRIPTION` file.
- [x] **Impact on Examples:** If your updates impact any examples, review locally for warnings or errors in the impacted example pages.
- [x] **Merge Conflicts:** Developers should address any merge conflicts and merge upon successful review.
- [x] **New Packages:** If new packages were used, ensure they are included in the `DESCRIPTION` file's `Imports` section.
- [x] **Updated Examples:** If you added or updated an example, ensure it runs on the latest CRAN release versions of all packages used.
- [x] **Testing Instructions:** Provide instructions on how to test the code if necessary.

### CODE REVIEW

**Comment by rossfarrugia** [comment]
@pawelru @jeffreyad any reason why the .R versions of these aren't getting automatically added? I thought that was done by the CI once we added:

```
invisible_hook_purl <- function(before, options, ...) {knitr::hook_purl(before, options, ...); NULL}
knitr::knit_hooks$set(purl = invisible_hook_purl)
```

When I try and render locally I get:

```
processing file: adrs.qmd
  |...                                           |   7% [setup script]         
Quitting from lines 7-9 [setup script] (adrs.qmd)
Error in `knitr::hook_purl()`:
! unused argument (`NA` = NULL)
Backtrace:
  1. global .main()
 16. global `<fn>`(before = FALSE, options = `<kntr_st_>`, `NA` = NULL)
                                                                                                                  
Execution halted
```

**Comment by pawelru** [comment]
Hmmm I don't know why you get errors like these. Just checked on `main` and all worked well on my local machine.
```
❯ quarto render adam/adrs.qmd

processing file: adrs.qmd
1/29                        
2/29 [setup script]         
3/29                        
4/29 [setup]                
5/29                        
6/29 [read-specs]           
7/29
(...)              
```

It also creates the script for me:
```
❯ git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        adam/adrs.R
```

If you are asking why they are missing on repo - they probably needs to be committed to the repo. I guess the best would be to have a bot to auto-commit this on each of the run on main. Either scheduled or executed right after merge.

**Comment by rossfarrugia** [comment]
ah i found it... i had {knitr} 1.44 instead of 1.48 latest from CRAN installed, it works now. thanks!

**Review by f-meister — APPROVED** [review]
LGTM. Definitely more readable now:

Screenshot 2024-10-08 at 6 58 45 PM

**Review by f-meister — APPROVED** [review]

**Pull request merged**
