### PR TITLE
run docs on push; deploy from main only

### PR DESCRIPTION
**Pull request by pawelru**
- run docs for each PR
- deploy only from main
- remove steps conditional on tags as we don't do the tags here
- update version of a few workflows

### CODE REVIEW

**Comment by rossfarrugia** [comment]
@bms63 @pawelru does this one still need merging? couldn't tell sorry from the slack chat

**Comment by pawelru** [comment]
Yes I think so. This would allow testing from the PR as opposed to merge blindly and wait for result from main. I think it's needed. We missed this somehow

**Comment by rossfarrugia** [comment]
OK thanks Pawel! As i'm still catching up post-holiday i tagged @bms63 here as reviewer to check he's happy and if so approve and merge.

**Comment by bms63** [comment]
I'm happy to merge this in, but I'm not sure what it is doing.

I always think of docs as `.Rd` files but this does something with the site?  Like it renders the site into a folder so we could take a look at it?

**Review by bms63 — APPROVED** [review]

**Comment by pawelru** [comment]
It's because it's a quarto book with `.qmd` articles as opposed to package vignette in `.Rmd`. On default, Quarto renders your book into the `_site` subdirectory which then you can _push_ to GH Pages (or not). This PR is just for include _rendering_ process (but not deploy!) for each PR or feature branch. This way we can test changes before they go into the main branch and that's the whole point of this change. Currently everything is going to main without us knowing whether the book is renderable or not.

I'm going ahead and merge it. Please let me know if you encounter any difficulities in the PRs

**Comment by bms63** [comment]
> It's because it's a quarto book with `.qmd` articles as opposed to package vignette in `.Rmd`. On default, Quarto renders your book into the `_site` subdirectory which then you can _push_ to GH Pages (or not). This PR is just for include _rendering_ process (but not deploy!) for each PR or feature branch. This way we can test changes before they go into the main branch and that's the whole point of this change. Currently everything is going to main without us knowing whether the book is renderable or not.
> 
> I'm going ahead and merge it. Please let me know if you encounter any difficulities in the PRs

Hey @pawelru that makes sense.  Thank you for explaining.  Maybe a section in the Readme around actions would be a nice to have?

**Pull request merged**
